# Generated by Django 4.1.5 on 2026-01-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='lasr_name',
            new_name='last_name',
        ),
    ]
